# Generated by Django 5.2.4 on 2025-07-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='이미지')),
                ('interest', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('star', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devtools.devtool')),
            ],
        ),
    ]
