# Generated by Django 5.2.4 on 2025-07-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='actor',
            new_name='actors',
        ),
    ]
