# Generated by Django 5.2.4 on 2025-07-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
